### PR TITLE
Allow multiple saga action types to map to the same simplesource comm…

### PR DESCRIPTION
**Pull request by wongelz**
…and topic

### CODE REVIEW

**Comment by szoio** [comment]
I'd like to question the premise that we want to be able to map multiple simple saga event sourcing actions to a single simple sourcing command.
As far as I am concerned, this action processor is just an adaptor - it allows you to plug a Simple Sourcing command into a saga. Simple Sourcing, rightly or wrongly, is already highly opiniated about how it processes commands. It's aggregate based - there is a single command processor that processes all the commands relating to an aggregate. So Simple Sourcing forces you to create polymorphic commands.
I don't see why a single action processor can't just pass through the command as is, and let simple sourcing deal with it. Having multiple action processors that map to a single simple sourcing command is promoting a confusing usage pattern.
If we don't like the way simple sourcing handles commands, and think that it should be split into multiple command processors for a single aggregate, I would prefer to address that in the Simple Sourcing project rather, and then let Simple Sagas inherit this pattern.

**Comment by szoio** [comment]
Further comments:
I'm happy with changes in general, there's a lot of good changes in the PR - more a principal of the usage - but that changes don't add too much complexity.
Btw I've added some test coverage in the `test-coverage` branch. This covers this action processor. It's not merged because it has a dependency on a snapshot version of simple sourcing. I would prefer to rebase this branch off that one.

**Comment by wongelz** [comment]
@szoio I think there may be some confusion here. By "map to the same simplesource command topic" I mean the single topic that handles all the commands for a given *aggregate*.

**Comment by wongelz** [comment]
One reason we can't pass through as-is, is we need to extract the aggregate-key (for the command/aggregate topic) from the action-value, which involves deserialization. Maybe we can do it if we had aggregate key as a field in ActionCommand, but that would make simplesagas closely tied with simplesouring...

**Comment by szoio** [comment]
> One reason we can't pass through as-is, is we need to extract the aggregate-key (for the command/aggregate topic) from the action-value

As it was previously, there was a `Function<I, K> keyMapper` parameter of the command spec that forced you to provide a mapping from the intermediate type to an aggregate key, without stipulating what a saga action looks like.
But I do prefer the builder interface you have here, and if you can find a way to get rid of the intermediate type `I` and find a way of getting from the action type `A` to `K` and `C` without double deserialising, I'd be happy. Not sure if it's possible though.

**Comment by wongelz** [comment]
Figured out a workaround to get this functionality working with the existing API.

**Pull request closed without merging**
